name: Trigger auto deployment for getmyage

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/getmyage-AutoDeployTrigger-a0896e08-5172-44f3-bbe5-9f6fdb6096b2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrgetmyage.azurecr.io
          username: ${{ secrets.GETMYAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.GETMYAGE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrgetmyage.azurecr.io/getmyage:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GETMYAGE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n getmyage -g my-container-apps-klj --server acrgetmyage.azurecr.io --username  ${{ secrets.GETMYAGE_REGISTRY_USERNAME }} --password ${{ secrets.GETMYAGE_REGISTRY_PASSWORD }}
            az containerapp update -n getmyage -g my-container-apps-klj --image acrgetmyage.azurecr.io/getmyage:${{ github.sha }}
